version: '3'

volumes:
  local_postgres_data:

services:
  beastz:
    build: ./
    ports:
      - '4000:4000'
    environment:
      DEBUG: /run/secrets/DEBUG
      PORT: ${PORT}
      PRISMA_ENGINE_PROTOCOL: /run/secrets/PRISMA_ENGINE_PROTOCOL
      MAX_FEEDBACK_PER_DAY_COUNT: /run/secrets/MAX_FEEDBACK_PER_DAY_COUNT
      FRONTEND_URL: /run/secrets/FRONTEND_URL
      BACKEND_URL: /run/secrets/BACKEND_URL
      ENABLE_SESSION_ACCESS_JWT_ENCRYPTION: /run/secrets/ENABLE_SESSION_ACCESS_JWT_ENCRYPTION
      DATABASE_URL: postgresql://postgres:A08X5fh4A5YKDS@db:5432/beastz?schema=public
      # DATABASE_URL: /run/secrets/DATABASE_URL
      DATABASE_LOG_QUERY: /run/secrets/DATABASE_LOG_QUERY
      MAIL_URL: /run/secrets/MAIL_URL
      MAIL_DOMAIN: /run/secrets/MAIL_DOMAIN
      MAIL_API_KEY: /run/secrets/MAIL_API_KEY
      MAIL_USERNAME: /run/secrets/MAIL_USERNAME
      MAIL_FROM: /run/secrets/MAIL_FROM
      COOKIE_SECRET: /run/secrets/COOKIE_SECRET
      ACCESS_TOKEN_EXPIRATION_IN_SEC: /run/secrets/ACCESS_TOKEN_EXPIRATION_IN_SEC
      REFRESH_TOKEN_EXPIRATION_IN_SEC: /run/secrets/REFRESH_TOKEN_EXPIRATION_IN_SEC
      RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC: /run/secrets/RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC
      RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC: /run/secrets/RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC
      ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC: /run/secrets/ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC
      ACCESS_TOKEN_SECRET: /run/secrets/ACCESS_TOKEN_SECRET
      REFRESH_TOKEN_SECRET: /run/secrets/REFRESH_TOKEN_SECRET
      SESSION_JWT_ENCRYPTION_KEY: /run/secrets/SESSION_JWT_ENCRYPTION_KEY
      ACCOUNT_VERIFY_TOKEN_SECRET: /run/secrets/ACCOUNT_VERIFY_TOKEN_SECRET
      RECOVER_PASSWORD_TOKEN_SECRET: /run/secrets/RECOVER_PASSWORD_TOKEN_SECRET
      RESET_PASSWORD_TOKEN_SECRET: /run/secrets/RESET_PASSWORD_TOKEN_SECRET
    depends_on:
      - db
    volumes:
      - /beastz-data/hub:/app/hub
      - /beastz-data/user-bin:/app/user-bin
      - /beastz-data/user-content:/app/user-content
      - /beastz-data/user-upload:/app/user-upload
      - /beastz-data/user-deleted-forever:/app/user-deleted-forever

  db:
    image: postgres:14.5-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USERNAME: /run/secrets/POSTGRES_USERNAME
      POSTGRES_DB: /run/secrets/POSTGRES_DB

    volumes:
      - local_postgres_data:/var/lib/postgresql/data
