version: '3'

volumes:
  local_postgres_data:

services:
  # beastz:
  #   build: ./
  #   ports:
  #     - '4000:4000'
  #   environment:
  #     DEBUG: ${DEBUG}
  #     PORT: ${PORT}
  #     PRISMA_ENGINE_PROTOCOL: ${PRISMA_ENGINE_PROTOCOL}
  #     MAX_FEEDBACK_PER_DAY_COUNT: ${MAX_FEEDBACK_PER_DAY_COUNT}
  #     FRONTEND_URL: ${FRONTEND_URL}
  #     BACKEND_URL: ${BACKEND_URL}
  #     ENABLE_SESSION_ACCESS_JWT_ENCRYPTION: ${ENABLE_SESSION_ACCESS_JWT_ENCRYPTION}
  #     DATABASE_URL: ${DATABASE_URL}
  #     DATABASE_LOG_QUERY: ${DATABASE_LOG_QUERY}
  #     MAIL_URL: ${MAIL_URL}
  #     MAIL_DOMAIN: ${MAIL_DOMAIN}
  #     MAIL_API_KEY: ${MAIL_API_KEY}
  #     MAIL_USERNAME: ${MAIL_USERNAME}
  #     MAIL_FROM: ${MAIL_FROM}
  #     COOKIE_SECRET: ${COOKIE_SECRET}
  #     ACCESS_TOKEN_EXPIRATION_IN_SEC: ${ACCESS_TOKEN_EXPIRATION_IN_SEC}
  #     REFRESH_TOKEN_EXPIRATION_IN_SEC: ${REFRESH_TOKEN_EXPIRATION_IN_SEC}
  #     RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC}
  #     RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC}
  #     ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC: ${ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC}
  #     ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  #     REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
  #     SESSION_JWT_ENCRYPTION_KEY: ${SESSION_JWT_ENCRYPTION_KEY}
  #     ACCOUNT_VERIFY_TOKEN_SECRET: ${ACCOUNT_VERIFY_TOKEN_SECRET}
  #     RECOVER_PASSWORD_TOKEN_SECRET: ${RECOVER_PASSWORD_TOKEN_SECRET}
  #     RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}
  #   depends_on:
  #     - db
  #   volumes:
  #     - /beastz-data/hub:/app/hub
  #     - /beastz-data/user-bin:/app/user-bin
  #     - /beastz-data/user-content:/app/user-content
  #     - /beastz-data/user-upload:/app/user-upload
  #     - /beastz-data/user-deleted-forever:/app/user-deleted-forever

  db:
    image: postgres:14.5-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'
      POSTGRES_USERNAME: '${{ secrets.POSTGRES_USERNAME }}'
      POSTGRES_DB: '${{ secrets.POSTGRES_DB }}'

      # POSTGRES_PASSWORD: A08X5fh4A5YKDS
      # POSTGRES_USERNAME: postgres
      # POSTGRES_DB: beastz

      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      # POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
