name: CD

on:
  push:
    branches: ['master']

env:
  DEBUG: ${{vars.DEBUG}}
  PORT: ${{vars.PORT}}
  PRISMA_ENGINE_PROTOCOL: ${{vars.PRISMA_ENGINE_PROTOCOL}}
  MAX_FEEDBACK_PER_DAY_COUNT: ${{vars.MAX_FEEDBACK_PER_DAY_COUNT}}
  FRONTEND_URL: ${{vars.FRONTEND_URL}}
  BACKEND_URL: ${{vars.BACKEND_URL}}
  ENABLE_SESSION_ACCESS_JWT_ENCRYPTION: ${{vars.ENABLE_SESSION_ACCESS_JWT_ENCRYPTION}}
  DATABASE_URL: ${{vars.DATABASE_URL}}
  DATABASE_LOG_QUERY: ${{vars.DATABASE_LOG_QUERY}}
  MAIL_URL: ${{vars.MAIL_URL}}
  MAIL_DOMAIN: ${{vars.MAIL_DOMAIN}}
  MAIL_API_KEY: ${{vars.MAIL_API_KEY}}
  MAIL_USERNAME: ${{vars.MAIL_USERNAME}}
  MAIL_FROM: ${{vars.MAIL_FROM}}
  COOKIE_SECRET: ${{vars.COOKIE_SECRET}}
  ACCESS_TOKEN_EXPIRATION_IN_SEC: ${{vars.ACCESS_TOKEN_EXPIRATION_IN_SEC}}
  REFRESH_TOKEN_EXPIRATION_IN_SEC: ${{vars.REFRESH_TOKEN_EXPIRATION_IN_SEC}}
  RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${{vars.RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC}}
  RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${{vars.RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC}}
  ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC: ${{vars.ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC}}
  ACCESS_TOKEN_SECRET: ${{vars.ACCESS_TOKEN_SECRET}}
  REFRESH_TOKEN_SECRET: ${{vars.REFRESH_TOKEN_SECRET}}
  SESSION_JWT_ENCRYPTION_KEY: ${{vars.SESSION_JWT_ENCRYPTION_KEY}}
  ACCOUNT_VERIFY_TOKEN_SECRET: ${{vars.ACCOUNT_VERIFY_TOKEN_SECRET}}
  RECOVER_PASSWORD_TOKEN_SECRET: ${{vars.RECOVER_PASSWORD_TOKEN_SECRET}}
  RESET_PASSWORD_TOKEN_SECRET: ${{vars.RESET_PASSWORD_TOKEN_SECRET}}

jobs:
  display-variables:
    runs-on: self-hosted
    steps:
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
          echo "variable from shell environment : $PORT"
        env:
          REPOSITORY_VAR: ${{ vars.DEBUG }}
          ORGANIZATION_VAR: ${{ vars.PORT }}
          OVERRIDE_VAR: ${{ vars.MAIL_URL }}

  # build:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: shut down the image
  #       run: docker compose down
  #     - name: remove dangling images
  #       run: docker image prune --all --force
  #     - name: rebuild the image
  #       run: docker compose build --no-cache
  #     - name: run the image
  #       run: docker compose up -d
#
# https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
